export const DECORATORS_PREFIX = 'asyncapi'
export const METADATA_FACTORY_NAME = '_ASYNCAPI_METADATA_FACTORY'
export const DECORATORS = {
  CHANNEL: `${DECORATORS_PREFIX}/channel`,
  MESSAGE: `${DECORATORS_PREFIX}/message`,
  SUB: `${DECORATORS_PREFIX}/sub`,
  PUB: `${DECORATORS_PREFIX}/pub`,
  API_MODEL_PROPERTIES: `${DECORATORS_PREFIX}/modelProperties`,
  API_MODEL_PROPERTIES_ARRAY: `${DECORATORS_PREFIX}/modelPropertiesArray`,
}
